name: neo4j
channels:
  - conda-forge
  - defaults
dependencies:
  # System Requirements
  - python=3.12.8
  - openjdk=11
  - pip

  # Core Data Processing (conda packages for better dependency resolution)
  - pandas=2.3.1
  - numpy=1.26.4
  - requests=2.31.0
  - tqdm=4.67.1
  - pyarrow=21.0.0

  # Testing Framework (conda packages)
  - pytest=8.4.1
  - pytest-cov=6.2.1
  - pytest-mock=3.14.1

  # Code Quality Tools (conda packages)
  - black=25.1.0
  - isort=6.0.1
  - flake8=7.1.2
  - mypy=1.17.0
  - bandit=1.8.6

  # Optional: Development tools
  - jupyter
  - psutil>=6.0.0

  # Pip-only packages (not available in conda-forge or require specific versions)
  - pip:
    # Neo4j and Spark (pip-only or specific versions)
    - neo4j==5.25.0
    - python-dotenv==1.1.1
    - pyspark==3.5.5
    - py4j==0.10.9.7
    - neo4j-parallel-spark-loader==0.5.2

    # Load Testing Framework (pip-only)
    - locust==2.37.14
    - faker>=30.0.0

    # Additional testing/quality tools (pip-only)
    - safety==3.6.0
    - types-requests==2.32.4.20250611
    - pandas-stubs==2.3.0.250703
