name: neo4j-flight-schedule
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.10
  
  # Core data processing
  - pandas>=1.5.0
  - numpy>=1.21.0
  - pyarrow>=10.0.0
  
  # Neo4j
  - pip
  - pip:
    - neo4j>=5.0.0
    - python-dotenv>=0.19.0
    - requests>=2.28.0
    - neo4j-parallel-spark-loader>=0.5.0
  
  # Spark ecosystem (for large dataset loading)
  - openjdk=11  # Required for Spark
  - pyspark=3.5.5  # Stable version compatible with Java 11
  - py4j>=0.10.9
  
  # Optional: Jupyter for data exploration
  - jupyter
  - matplotlib
  - seaborn
  
  # Development tools
  - pytest
  - black>=22.0.0
  - isort>=5.10.0  
  - flake8>=4.0.0
  - flake8-docstrings