name: neo4j
channels:
  - conda-forge
  - defaults
dependencies:
  # System Requirements
  - python=3.12.8
  - openjdk=11
  - pip

  # Core Data Processing
  - pip:
    # Core Data Processing
    - neo4j==5.25.0
    - pandas==2.3.1
    - pyarrow==21.0.0
    - numpy==1.26.4
    - requests==2.31.0
    - python-dotenv==1.1.1
    - tqdm==4.67.1

    # Apache Spark (REQUIRED - not optional)
    - pyspark==3.5.5
    - py4j==0.10.9.7

    # Neo4j Spark Integration
    - neo4j-parallel-spark-loader==0.5.2

    # Testing Framework (Required for CI/CD)
    - pytest==8.4.1
    - pytest-cov==6.2.1
    - pytest-mock==3.14.1

    # Code Quality Tools (Required for CI/CD)
    - black==25.1.0
    - isort==6.0.1
    - flake8==7.1.2
    - mypy==1.17.0
    - bandit==1.8.6
    - safety==3.6.0

    # Type Stubs for Better Development
    - types-requests==2.32.4.20250611
    - pandas-stubs==2.3.0.250703

    # Load Testing Framework
    - locust==2.37.14
    - faker==32.8.4

  # Optional: Jupyter for data exploration
  - jupyter
  - psutil>=6.0.0
